### ISSUE TITLE
Error while threading using CLI

### ISSUE THREAD

**Issue by SeMoOo** [EchterAlsFake/PHUB#67]
There is an error when using the CLI command for threaded download. The output is:

Error: threaded() got an unexpected keyword argument 'video'. 

Default and FFMPEG options work fine.

**Comment by EchterAlsFake** [comment]
So I have completely rewritten the CLI since it was very outdated.
Could you please install PHUB from GitHub real quick? You can do this by:

`pip uninstall phub`
`pip install git+https://github.com/EchterAlsFake/PHUB`

And then try it again? Please note that since the rewrite some things changed. Please run `phub --help` to see the new options. Should explain everything by itself (hopefully).

If that doesn't fix the issue or it did (no matter what), please tell me the result. If everything is working so far, I will release the new version of PHUB with those changes to PyPi. 


Thank you a lot for reporting this. Would have probably overlooked it for the next 2 years lol.

**Comment by SeMoOo** [comment]
I noticed that the video output codecs are somehow different. Both are .mp4 (MPEG-4) but using ffprone you get two different results. Also the new CLI version output does not work on iOS default player. Using 3rd party apps plays the video but not as smoothly.

**Comment by EchterAlsFake** [comment]
Hi, the issue with the codecs is, because the video segments are `.ts` files which are used by streaming services. They are all packed together into a .mp4 container, but it's just named mp4. There isn't a real "formatting" process behind it. Most video players will work just fine and since I already fixed that in Porn Fetch I thought that I wouldn't need that anymore, but you are of course totally right.

So my solution would be, that I add a function in PHUB (generally, not just the CLI) to convert every video after downloading to mp4. This would be an optional argument for a user when downloading videos. Converting the videos would need ffmpeg, however, because it's not entirely re-encoded it would basically need almost no time. Probably a process of 2-5 seconds.

Do you think this would be okay?

**Comment by SeMoOo** [comment]
Thank you for your prompt response. Well, I am not an expert nor a hardcore programmer but I believe an argument would be a good option. Would like to have a seperate branch for me to test on iOS environment?

**Comment by EchterAlsFake** [comment]
Okay perfect. I will start implementing it tomorrow, and tell you when it's done :)

**Comment by EchterAlsFake** [comment]
Sorry that this took so long, but it's now done.

You can enable FFmpeg converting using:

```python
from phub import Client
video = Client().get_video("some video")
video.download(..... convert=True)
```

Using the `convert` argument. By default PHUB will search in your system's path for FFmpeg, but you can define a custom path using `consts.FFMPEG_EXECUTABLE`

I hope this works so far :)
