### ISSUE TITLE
how to get directlink url mp4 without token

### ISSUE THREAD

**Issue by joesandiroz2** [EchterAlsFake/PHUB#68]
i find and use you example script . but i want get directlink mp4 without token or whatever . because i want remote upload to my video hosting . like streamwish , vidhide . how to solve thx

```
import phub
# from phub.locals import *

client = phub.Client()
url = 'https://www.pornhub.com/view_video.php?viewkey=66ba248671e4e'
video = client.get(url) 

# print(dir(video))
print(video.get_direct_url(quality=720))
```

**Comment by EchterAlsFake** [comment]
Hi, there is no direct link for videos. All uploaded videos on PornHub and mostly other platforms are using segments. They basically split a video into smaller fragments to allow for a variable bitrate when streaming the video. The ony method you can use is download through the video.download() function and use that video, but at least from my side I don't want to encourage you to mass distribute content on other platforms, because this gives a negative purpose to my / Egsagons project. 

The same goes for xvideos where you reported the same issue.

**Comment by Egsagon** [comment]
If you really don't want to download videos locally, you can use get_direct_url or a custom loader, and a proxy to transfer your video. Either way, **you cannot just pass the URL to your remote service**, you must have an intermediate step.
